site_name: CanisMajor
site_url: https://canismajor.readthedocs.io
repo_url: https://github.com/fiware/CanisMajor/docs
site_description: CanisMajor Documentation
docs_dir: docs
site_dir: html
edit_uri: edit/master/docs/
markdown_extensions: [toc, fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css:
    [
        "https://www.fiware.org/style/fiware_readthedocs.css",
        "https://www.fiware.org/style/fiware_readthedocs_iot.css",
    ]
pages:
    - Home: index.md
    - "Installation": installation.md
    - "APIs": apis.md
